import {test, expect} from '@playwright/test';

test('desktop panels resize independently and collapsed tools have hover and focus tooltips', async ({page}) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page).toHaveTitle(/Vesta/);
  await page.getByLabel('Report text', {exact:true}).fill('Preserve this draft');
  const input = page.getByLabel('Report text', {exact:true});
  const fullWidth = (await input.boundingBox())!.width;
  const studioHeadingX = (await page.getByRole('heading',{name:'QA Studio',exact:true}).boundingBox())!.x;
  await page.screenshot({path:'/tmp/radbench-panels-expanded.png'});
  await page.getByRole('button',{name:'Collapse Report reviews',exact:true}).click();
  expect((await input.boundingBox())!.width).toBeGreaterThan(fullWidth);
  const leftCollapsedWidth = (await input.boundingBox())!.width;
  expect((await page.getByRole('heading',{name:'QA Studio',exact:true}).boundingBox())!.x).toBe(studioHeadingX);
  await page.getByRole('button',{name:'Collapse QA Studio',exact:true}).click();
  expect((await input.boundingBox())!.width).toBeGreaterThan(leftCollapsedWidth);
  const labels = ['New review','Review history','Feedbacks','Analytics','Skills','Playground'];
  for (const name of labels) {
    const button = page.getByRole('button',{name,exact:true});
    await button.hover();
    const tooltip = page.getByRole('tooltip',{name,exact:true});
    await expect(tooltip).toBeVisible();
    const box = (await tooltip.boundingBox())!;
    expect(box.x).toBeGreaterThanOrEqual(0);
    expect(box.x+box.width).toBeLessThanOrEqual(1536);
    await tooltip.hover();
    await expect(tooltip).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(tooltip).toBeHidden();
    await page.mouse.move(600,0);
    await button.focus();
    await expect(tooltip).toBeVisible();
    await button.press('Escape');
    await expect(tooltip).toBeHidden();
    await expect(button).toBeFocused();
  }
  await page.getByRole('button',{name:'Skills',exact:true}).focus();
  await page.getByRole('button',{name:'Skills',exact:true}).hover();
  await page.screenshot({path:'/tmp/radbench-panels-collapsed.png'});
  await page.getByRole('button',{name:'Skills',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Skills',exact:true})).toBeVisible();
  await page.getByRole('textbox',{name:'Draft content',exact:true}).fill('Unsaved skill edit');
  await page.getByRole('button',{name:'Current review',exact:true}).click();
  await expect(input).toHaveValue('Preserve this draft');
  await page.getByRole('button',{name:'Expand QA Studio',exact:true}).click();
  expect((await input.boundingBox())!.width).toBe(leftCollapsedWidth);
  await page.getByRole('button',{name:'Skills',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Draft content',exact:true})).toHaveValue('Unsaved skill edit');
  await page.reload();
  await expect(page.getByRole('button',{name:'Expand Report reviews',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Collapse QA Studio',exact:true})).toBeVisible();
  expect(errors).toEqual([]);
});

test('compact panels open one at a time and mobile drawers trap and restore focus', async ({page}) => {
  await page.goto('/');
  await page.getByLabel('Report text',{exact:true}).fill('Draft across widths');
  await page.setViewportSize({width:900,height:900});
  await expect(page.getByRole('button',{name:'Expand Report reviews',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Expand QA Studio',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Expand Report reviews',exact:true}).click();
  await page.getByRole('button',{name:'Expand QA Studio',exact:true}).click();
  await expect(page.getByRole('button',{name:'Expand Report reviews',exact:true})).toBeVisible();
  await page.screenshot({path:'/tmp/radbench-panels-tablet.png'});
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByLabel('Report text',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Open QA Studio',exact:true}).click();
  const studio = page.getByRole('dialog',{name:'QA Studio',exact:true});
  await expect(studio).toBeVisible();
  await expect(studio.getByRole('button',{name:'Close QA Studio',exact:true})).toBeFocused();
  await page.keyboard.press('Shift+Tab');
  await expect(studio.getByRole('button',{name:'Playground',exact:true})).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(studio.getByRole('button',{name:'Close QA Studio',exact:true})).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(studio).toBeHidden();
  await expect(page.getByRole('button',{name:'Open QA Studio',exact:true})).toBeFocused();
  await page.getByRole('button',{name:'Open QA Studio',exact:true}).click();
  await page.getByRole('button',{name:'Skills',exact:true}).click();
  await expect(studio).toBeHidden();
  await expect(page.getByRole('heading',{name:'Skills',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Open Report reviews',exact:true}).click();
  const reports = page.getByRole('dialog',{name:'Report reviews',exact:true});
  await expect(reports).toBeVisible();
  await page.getByRole('button',{name:'Current review',exact:true}).click();
  await expect(reports).toBeHidden();
  await expect(page.getByLabel('Report text',{exact:true})).toHaveValue('Draft across widths');
  await page.screenshot({path:'/tmp/radbench-panels-mobile.png'});
  await page.getByRole('button',{name:'Open QA Studio',exact:true}).click();
  await page.screenshot({path:'/tmp/radbench-panels-drawer.png'});
  await page.mouse.click(8,400);
  await expect(studio).toBeHidden();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:1536,height:1024});
  await expect(page.getByRole('button',{name:'Collapse Report reviews',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Collapse QA Studio',exact:true})).toBeVisible();
});

test('collapsed Studio keeps actual review status visible and can reveal all phases', async ({page,request}) => {
  const config = await (await request.get('/api/v1/config')).json();
  await page.goto('/');
  await page.getByRole('button',{name:'Collapse QA Studio',exact:true}).click();
  await page.getByLabel('Report text',{exact:true}).fill(config.samples.find((sample:{id:string})=>sample.id==='mixed').report_text);
  await page.getByRole('button',{name:'Review',exact:true}).click();
  await expect(page.locator('#input-help[role="status"]')).toHaveText('Output ready.');
  await expect(page.locator('.review-journey .complete')).toHaveCount(4);
  await expect(page.getByText('AI review',{exact:true})).toBeVisible();
});
