"""Build the standalone prototype blueprint and implementation edition; Python stdlib only."""
from pathlib import Path
import ast, html, json
r=Path(__file__).resolve().parent
# Reuse only the existing controlled-Markdown renderer's imports and functions.
source=ast.parse((r.parent/'framework/render_blueprint.py').read_text(encoding="utf-8"))
allowed=[n for n in source.body if isinstance(n,(ast.Import,ast.ImportFrom,ast.FunctionDef))]
ns={'r':r}
exec(compile(ast.Module(body=allowed,type_ignores=[]),'<markdown-renderer>','exec'),ns)
sections=[('FOUNDATION_PLAN.md','foundation','Foundation plan'),('FOUNDATION_CHANGELOG.md','changes','Implemented phases'),('WORKSPACE_SPEC.md','workspace','Workspace'),('ANALYTICS_SPEC.md','analytics','Analytics'),('SKILLS_STUDIO_SPEC.md','skills-studio','Skills Studio'),('REFINEMENT_SPEC.md','refinement','Refinement baseline'),('IMPLEMENTATION_STATUS.md','status','Built & tested'),('BLUEPRINT.md','blueprint','Blueprint'),('UX_DESIGN_SYSTEM.md','design','Design system'),('UX_STATES.md','states','UX states'),('ROADMAP.md','roadmap','Roadmap'),('API_DESIGN.md','api','API'),('IMPLEMENTATION_PLAN.md','implementation','Implementation'),('DBOS_VALIDATION.md','dbos','DBOS'),('ACCEPTANCE.md','acceptance','Acceptance'),('REVIEW_NOTES.md','review','Decisions'),('TESTING_EXPLAINED.md','testing','Sample tests'),('API_REVIEW.md','api-review','API review')]
css='''*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:80px}body{margin:0;background:#f5f6f8;color:#20242b;font:16px/1.65 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{padding:42px max(5vw,24px) 30px;background:white;border-bottom:1px solid #dde2e8}.brand{font-weight:650;color:#59616d}.brand b{color:#20242b}h1{font-size:38px;line-height:1.2;letter-spacing:-1px;margin:20px 0 14px;max-width:850px}header p{max-width:850px;color:#59616d}.state{font-size:13px;color:#59616d}.phasebar{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:#dde2e8;border:1px solid #dde2e8;max-width:1050px;margin-top:28px}.phasebar div{background:#fafbfc;padding:16px}.phasebar b{display:block;font-size:14px}.phasebar span{color:#59616d;font-size:13px}nav{position:sticky;top:0;display:flex;gap:20px;flex-wrap:wrap;padding:15px max(5vw,24px);background:#fff;border-bottom:1px solid #dde2e8;z-index:2;font-size:14px}a{color:#245bb2;text-underline-offset:3px}main{max-width:1160px;margin:auto;background:#fff;padding:16px 46px 50px}section{padding-top:20px}h2{font-size:29px;line-height:1.3;margin-top:40px;border-top:2px solid #dde2e8;padding-top:22px}h3{font-size:21px;margin-top:32px}h4{font-size:18px}p{max-width:970px}table{border-collapse:collapse;width:100%;font-size:14px;line-height:1.55}td,th{text-align:left;vertical-align:top;padding:12px;border-bottom:1px solid #dde2e8}th{background:#f0f2f5;font-weight:600}.table-wrap{overflow:auto;margin:20px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f5f6f8;padding:18px;border-left:3px solid #737d8c;font-size:13px}code{font-family:ui-monospace,monospace}figure{margin:24px 0}figure img{width:100%;height:auto;border:1px solid #dde2e8}figcaption{color:#59616d;font-size:13px;margin-top:8px}footer{padding:30px;text-align:center;color:#59616d;font-size:13px}@media(max-width:700px){main{padding:12px 18px}h1{font-size:29px}nav{gap:12px;padding:12px 18px}.phasebar{grid-template-columns:repeat(2,1fr)}td,th{min-width:120px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}@media print{nav{position:static}main{padding:0}body{background:white}.phasebar{break-inside:avoid}tr{break-inside:avoid}h2,h3{break-after:avoid}}'''
nav=''.join(f'<a href="#{key}">{label}</a>' for _,key,label in sections)
phases=[('F1. Contracts','Fresh schema and generated types'),('F2. Content','Pinned references and tenant snapshots'),('F3. Execution','Single-call DBOS and spend guard'),('F4. Regression','Preserve features and verify artifacts'),('F5. Evaluation','Separate permission and clinical review')]
bar=''.join(f'<div><b>{title}</b><span>{desc}</span></div>' for title,desc in phases)
body=''.join(f'<section id="{key}">'+ns['render']((r/name).read_text(encoding="utf-8"),key)+'</section>' for name,key,_ in sections)
data=json.loads((r/'examples/scenarios.json').read_text(encoding="utf-8"))
body+='<section id="examples"><h2>Synthetic seed examples</h2><p>Proposed behavior for review; no clinical or model validation claimed.</p>'
for c in data['cases']:
 body+='<h3>'+html.escape(c['acceptance_id']+' · '+c['name'])+'</h3><pre>'+html.escape(c['report_text'])+'</pre><p>'+html.escape(c['expected_behavior'])+'</p>'
body+='</section>'
page='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vesta Report QA — Prototype blueprint and phased plan</title><style>'+css+'</style></head><body><header><div class="brand"><b>Vesta</b> / Report QA</div><h1>Clean-start foundations for the existing QA workspace</h1><p>API-first contracts, fresh application and DBOS stores, and one combined model request. Preserve history, feedback, analytics and tenant-scoped authoring.</p><div class="state">Plan revised 17 September 2026 · Application 0.12.0 · F1/F2 implemented · F3–F5 pending</div><div class="phasebar">'+bar+'</div></header><nav>'+nav+'<a href="#examples">Examples</a></nav><main>'+body+'</main><footer>Documentation revision 2026-09-17; application 0.12.0 / bundle 1.16. F1/F2 implemented; no clinical validation implied. This is the reading edition; use README.md to run the application.</footer></body></html>'
(r/'BLUEPRINT.html').write_text(page, encoding='utf-8')
print('Built prototype/BLUEPRINT.html')
